title: Owenll66's blog site
description:
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
permalink: /:categories/:year/:month/:day/:title

#paging
paginate: 6
paginate_path: "/posts/page:num/"

highlighter: rouge

#SEO
plugins:
  - jekyll-seo-tag
