title: Blog site
description: Computer Science knowledge is worth sharing!
show_downloads: true
google_analytics: UA-143383051-1
theme: jekyll-theme-cayman
permalink: /:categories/:year/:month/:day/:title

#paging
paginate: 6
paginate_path: "/posts/page:num/"

highlighter: rouge

#SEO
plugins:
  - jekyll-seo-tag
